"""empty message

Revision ID: 12b3684e31e7
Revises: 41f8806686bc
Create Date: 2015-11-24 09:23:51.069041

"""

# revision identifiers, used by Alembic.
revision = '12b3684e31e7'
down_revision = '41f8806686bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object2user', sa.Column('locked', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object2user', 'locked')
    ### end Alembic commands ###
