"""empty message

Revision ID: 142127e3c14a
Revises: 50c29fb55f68
Create Date: 2015-11-26 10:30:30.796003

"""

# revision identifiers, used by Alembic.
revision = '142127e3c14a'
down_revision = '50c29fb55f68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('max_points', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'max_points')
    ### end Alembic commands ###
