"""empty message

Revision ID: 41f8806686bc
Revises: 18b470965629
Create Date: 2015-11-24 09:19:51.450703

"""

# revision identifiers, used by Alembic.
revision = '41f8806686bc'
down_revision = '18b470965629'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object2user', sa.Column('txt', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object2user', 'txt')
    ### end Alembic commands ###
